[phases.setup]
nixPkgs = ["nodejs_22", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm install --prefix artifacts/discord-bot",
  "npm install --prefix artifacts/utility-bot",
]

[start]
cmd = "node start.js"
